# this is comment.
version: "3"

services:
  backend:
    container_name: django-backend
    env_file: ./backend/sxa/.env
    build: ./backend/sxa/.
    volumes:
      - ./backend/sxa/:/code/
      - static_volume:/code/staticfiles 
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 sxa.wsgi:application
    networks:
      - backend_network
    depends_on:
      - database
  backend-server:
    container_name: nginx-backend
    build: ./backend/nginx/.
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - backend_network
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: testuser
      POSTGRES_USER: testuser
      POSTGRES_DB: clustering
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend_network
  
  frontend:
    container_name: react
    build: 
      context: ./frontend
      target: develop-stage
    volumes:
      - ./frontend/app:/app
    ports:
      - "3000:3000"
    networks:
      - frontend_network
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  # frontend-server:
  #   container_name: nginx-frontend
  #   build: ./frontend/nginx/.
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
volumes:
  static_volume:
