# this is comment.
version: "3"

services:
  app-back:
    container_name: django-backend
    env_file: ./backend/sxa/.env
    build: ./backend/sxa/.
    volumes:
      - ./backend/sxa/:/code/
      - static_volume:/code/staticfiles 
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 sxa.wsgi:application
    networks:
      - backend_network
    depends_on:
      - database
  backend-server:
    container_name: nginx-backend
    build: ./backend/nginx/.
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8080:80"
    depends_on:
      - app-back
    networks:
      - backend_network
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: testuser
      POSTGRES_USER: testuser
      POSTGRES_DB: clustering
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend_network
  
  app-front:
    image: node:18
    volumes:
      - ./frontend/sxa-ui:/home/app/frontend
    ports:
      - "3000:3000"
    working_dir: /home/app/frontend
    user: node
    command: [bash, -c, yarn upgrade --no-progress --network-timeout 1000000 && yarn run dev]
    networks:
      - frontend_network
  frontend-server:
    container_name: nginx-frontend
    build: ./frontend/nginx/.
    ports:
      - "80:80"
    depends_on:
      - app-front
    networks:
      - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
volumes:
  static_volume:
